apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  name: mc-oci-java
spec:
  container: mc-server # GameServer
  ports:
  - name: mc-oci
    portPolicy: Dynamic   #
    container: mc-server
    containerPort: 25565
    protocol: TCP
  health:
    initialDelaySeconds: 300
    periodSeconds: 12
    failureThreshold: 5
  template:
    spec:
      containers:
        - name: mc-server
          image: itzg/minecraft-server # Minecraft Java server image
          env: # Full list of ENV variables at https://github.com/itzg/docker-minecraft-server
            - name: EULA
              value: "TRUE"
            - name: MAX_MEMORY
              value: "3G"
            - name: INIT_MEMORY
              value: "3G"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data
              name: world-vol
          ports:
            - containerPort: 25575 # exposes the RCON port to within the cluster from the pod's IP
        - name: mc-monitor
          image: iad.ocir.io/idi2cuxxbkto/piday/mc-monitor-agones-java:latest
          env:
            - name: PING_INTERVAL
              value: "10"
            - name: MC_TIMEOUT
              value: "10"
            - name: MAX_ATTEMPTS
              value: "20"
            - name: WARMUP_TIME
              value: "60"
          imagePullPolicy: Always

        - name: mc-backup
          image: iad.ocir.io/idi2cuxxbkto/piday/mc-oci-backup:latest
          args:
            - backup
          env:
            - name: BUCKET_NAME
              value: "j2joib" #"agones-minecraft-mc-worlds"
            - name: BACKUP_CRON
              value: "0 * */6 * *"
            - name: INITIAL_DELAY
              value: "60s"
            - name: VOLUME
              value: "/data"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RCON_PASSWORD
              value: minecraft
            - name: ENVIRONMENT
              value: "development"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data # shared vol with mc-server
              name: world-vol

      volumes:
        - name: world-vol # shared vol between containers. will not persist bewteen restarts
      imagePullSecrets:
        - name: ocirpiday
