apiVersion: "agones.dev/v1"
kind: GameServer
metadata:
  # generateName: "mc-mjava" # generate a unique name, with the given prefix
  name: mc-oci-java
spec:
  container: mc-server # Minecraft server container name
  ports:
  - name: mc-oci
    # "Dynamic" (default) the system allocates a free hostPort for the gameserver (default 7000-8000), for game clients to connect to
    portPolicy: Dynamic
    # The name of the container to open the port on. Defaults to the game server container if omitted or empty.
    container: mc-server
    # the port that is being opened on the game server process
    containerPort: 25565
    # Minecraft uses TCP to connect players
    protocol: TCP
  # Health checking for the running game server
  health:
    # Number of seconds after the container has started before health check is initiated.
    initialDelaySeconds: 300
    # If the `Health()` function doesn't get called at least once every period (seconds), then
    # the game server is not healthy.
    periodSeconds: 12
    # Minimum consecutive failures for the health probe to be considered failed after having succeeded.
    failureThreshold: 5
  template:
    spec:
      containers:
        - name: mc-server
          image: itzg/minecraft-server # Minecraft Java server image
          env: # Full list of ENV variables at https://github.com/itzg/docker-minecraft-server
            - name: EULA
              value: "TRUE"
            - name: MAX_MEMORY
              value: "3G"
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /data # shared vol with mc-load and mc-backup
              name: world-vol
          ports:
            - containerPort: 25575 # exposes the RCON port to within the cluster from the pod's IP

        - name: mc-monitor
          image: iad.ocir.io/idi2cuxxbkto/piday/mc-monitor-agones-java:latest
          env:
            - name: PING_INTERVAL
              value: "10"
            - name: MC_TIMEOUT
              value: "10"
            - name: MAX_ATTEMPTS
              value: "5"
            - name: WARMUP_TIME
              value: "60"
          imagePullPolicy: Always

        - name: mc-backup
          image: iad.ocir.io/idi2cuxxbkto/piday/agones-mc-oci:0.1.2
          args:
            - backup
          env:
            - name: BUCKET_NAME
              value: "j2joib" #"agones-minecraft-mc-worlds"
            - name: BACKUP_CRON
              value: "0 * */6 * *"
            - name: INITIAL_DELAY
              value: "60s"
            - name: VOLUME
              value: "/data"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # GameServer ref for naming backup zip files
            - name: RCON_PASSWORD
              value: minecraft # default rcon password. If provided RCON connection will be used to execute 'save-all' before a backup job.
              # Change the rcon password when exposing RCON port outside the pod
            - name: ENVIRONMENT
              value: "development"
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data # shared vol with mc-server
              name: world-vol

      volumes:
        - name: world-vol # shared vol between containers. will not persist bewteen restarts
      imagePullSecrets:
        - name: ocirsecret
