apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: mc-oci-java
spec:
  replicas: 2
  scheduling: Packed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        game: mc-oci
        edition: java
      annotations:
        external-dns.alpha.kubernetes.io/hostname: piday.com
        external-dns.alpha.kubernetes.io/gameserver-service: minecraft
    spec:
      container: mc-server # Minecraft server container name
      ports:
        - name: mc-oci
          portPolicy: Dynamic
          container: mc-server
          containerPort: 25565
          protocol: TCP
      health:
        initialDelaySeconds: 300
        periodSeconds: 12
        failureThreshold: 5
      template:
        spec:
          containers:
            - name: mc-server
              image: itzg/minecraft-server # Minecraft Java server image
              env: # Full list of ENV variables at https://github.com/itzg/docker-minecraft-server
                - name: EULA
                  value: "TRUE"
                - name: MAX_MEMORY
                  value: "3G"
                - name: INIT_MEMORY
                  value: "3G"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /data # shared vol with mc-load and mc-backup
                  name: world-vol
              ports:
                - containerPort: 25575 # exposes the RCON port to within the cluster from the pod's IP

            - name: mc-monitor
              image: iad.ocir.io/idi2cuxxbkto/piday/mc-monitor-agones-java:latest
              env:
                - name: PING_INTERVAL
                  value: "10"
                - name: MC_TIMEOUT
                  value: "10"
                - name: MAX_ATTEMPTS
                  value: "20"
                - name: WARMUP_TIME
                  value: "100"
              imagePullPolicy: Always

            - name: mc-backup
              image: iad.ocir.io/idi2cuxxbkto/piday/mc-oci-backup:latest
              args:
                - backup
              env:
                - name: BUCKET_NAME
                  value: "j2joib" #"agones-minecraft-mc-worlds"
                - name: BACKUP_CRON
                  value: "0 */6 * * *"
                - name: INITIAL_DELAY
                  value: "60s"
                - name: VOLUME
                  value: "/data"
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name # GameServer ref for naming backup zip files
                - name: RCON_PASSWORD
                  value: minecraft # default rcon password. If provided RCON connection will be used to execute 'save-all' before a backup job.
                  # Change the rcon password when exposing RCON port outside the pod
                - name: ENVIRONMENT
                  value: "development"
              imagePullPolicy: IfNotPresent
              volumeMounts:
                - mountPath: /data # shared vol with mc-server
                  name: world-vol

          volumes:
            - name: world-vol # shared vol between containers. will not persist between restarts
          imagePullSecrets:
            - name: ocirsecret    
